# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_student_rf_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='course',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='basic.Course'),
        ),
    ]
