# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_courseclass_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='end_time',
            field=models.CharField(default=b'2009-01-05 22:14:39', max_length=20),
        ),
        migrations.AddField(
            model_name='semester',
            name='start_time',
            field=models.CharField(default=b'2009-01-05 22:14:39', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='course_class',
            field=models.ManyToManyField(to='basic.CourseClass'),
        ),
    ]
